apiVersion: v1
kind: Service
metadata:
  name: kubepulse
  labels:
    app: kubepulse
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: kubepulse
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubepulse
  labels:
    app: kubepulse
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - kubepulse.example.com
    secretName: kubepulse-tls
  rules:
  - host: kubepulse.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kubepulse
            port:
              number: 80