apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepulse
spec:
  template:
    spec:
      containers:
      - name: kubepulse
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi