apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namePrefix: prod-

commonLabels:
  environment: production

images:
- name: ghcr.io/charles-adedotun/kubepulse
  newTag: latest

replicas:
- name: kubepulse
  count: 5

patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml