apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubepulse
spec:
  tls:
  - hosts:
    - kubepulse.example.com
    secretName: kubepulse-tls
  rules:
  - host: kubepulse.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-kubepulse
            port:
              number: 80