apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepulse
spec:
  template:
    spec:
      containers:
      - name: kubepulse
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: LOG_LEVEL
          value: "debug"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi