apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namePrefix: staging-

commonLabels:
  environment: staging

images:
- name: ghcr.io/charles-adedotun/kubepulse
  newTag: staging

replicas:
- name: kubepulse
  count: 2

patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml