name: Minimal CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Working Packages
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: true
    
    - name: Test working packages
      run: |
        # Test only packages that currently build and have tests
        echo "Testing working packages..."
        go test -v ./pkg/core/...
        go test -v ./pkg/plugins/...
        go test -v ./pkg/k8s/...
        go test -v ./pkg/health/...
        go test -v ./pkg/alerts/...
        go test -v ./pkg/ml/...
        go test -v ./pkg/slo/...
        
    - name: Basic lint check
      run: |
        # Basic gofmt check
        if [ -n "$(gofmt -l .)" ]; then
          echo "The following files need gofmt:"
          gofmt -l .
          exit 1
        fi
        echo "✅ All files are properly formatted"
        
    - name: Go vet check
      run: |
        # Only vet packages that build
        go vet ./pkg/core/...
        go vet ./pkg/plugins/...
        go vet ./pkg/k8s/...
        go vet ./pkg/health/...
        go vet ./pkg/alerts/...
        go vet ./pkg/ml/...
        go vet ./pkg/slo/...
        echo "✅ Go vet passed"

  # TODO: Add Claude Code Review integration once action is available
  # claude-review:
  #   name: Claude Code Review
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'pull_request'